# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e63c2a8d707121d26b7ec74bd64d61e90b81da8e1875a6db155da537b1ac74dd7db70b5318b9f1c2c1ca215ea3b67562840aec3d092281a3ccff7bd89e72ae

test:
  secret_key_base: 9f347b1a5c56cf1f6069d7cf7b6d9f950b4674871efe0ecb6e21e9fdba58b99365544472d1e30e6723e0bcecd6d747e4e192301383fbbc351578d586804fd059

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
